modLoader="javafml" 
loaderVersion="[36,)"
issueTrackerURL="https://github.com/owmii/lost-trinkets/issues"
license="LGPLv3"

[[mods]]
modId="losttrinkets"
version="${file.jarVersion}"
displayName="Lost Trinkets"
displayURL="https://www.curseforge.com/minecraft/mc-mods/lost-trinkets"
authors="owmii"
description='''
70+ Unlockable trinkets with different useful abilities.
'''

[[dependencies.losttrinkets]]
    modId="lollipop"
    mandatory=true
    versionRange="[3.2.9,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.losttrinkets]]
    modId="forge"
    mandatory=true
    versionRange="[36.0.0,)"
    ordering="NONE"
    side="BOTH"